service:
  address: 127.0.0.1:27001

tinkoff-client:
  url: https://invest-public-api.tinkoff.ru:443
  auth_token: <token>

instrument-sync:
  update_period: 600

mongo:
  url: mongodb://127.0.0.1:27017

strategy-registry: {}

instrument-cache:
  update_period: 10

strategy-cache:
  update_period: 5
