service:
  address: 127.0.0.1:27001

tinkoff-client:
  url: https://invest-public-api.tinkoff.ru:443
  sandbox_auth_token: <token>
  production_auth_token: <token>

instrument-sync:
  update_period: 600

mongo:
  url: mongodb://127.0.0.1:27017

strategy-registry: {}

instrument-cache:
  update_period: 10

strategy-cache:
  update_period: 1

market-data-sync:
  update_period: 10
  max_chunks_per_instrument: 10

strategy-runner:
  update_period: 1

accounts-cache:
  update_period: 600

positions-cache:
  update_period: 5

param-validator: {}

position-manager-registry: {}

position-manager-cache:
  update_period: 1

position-manager-runner:
  update_period: 1
  max_execution_context_age: 60
